<?php
session_start();
require("config.php");
$OBJ = new baocaothue();
{
    $OBJ->re_query("delete from tokhaitndn");
if ($_SESSION['theothongtu'] == "tt200") {
    $OBJ->re_query("INSERT INTO `tokhaitndn` (`sott`, `maso`, `chitieu`, `machitieu`, `sotien`, `machitieucha`, `loaitokhai`, `matk`, `tkno`, `sotiendk`) VALUES
											(2, '1', 'Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp', 'A1', 21444076949, 'A', 'TNDN', '', '', 0),
											(3, 'B', 'Xác định thu nhập chịu thuế theo Luật thuế thu nhập doanh nghiệp', 'B', 0, '0', 'TNDN', '', '', 0),
											(4, '1', 'Điều chỉnh tăng tổng lợi nhuận trước thuế thu nhập doanh nghiệp  (B1= B2+B3+B4+B5+B6 +B7)', 'B1', 0, 'B', 'TNDN', '', '', 0),
											(5, '1.1', 'Các khoản điều chỉnh tăng doanh thu', 'B2', 0, 'B', 'TNDN', '', '', 0),
											(6, '1.2', 'Chi phí của phần doanh thu điều chỉnh giảm', 'B3', 0, 'B', 'TNDN', '', '', 0),
											(7, '1.3', 'Các khoản chi không được trừ khi xác định thu nhập chịu thuế', 'B4', 0, 'B', 'TNDN', '', '', 0),
											(8, '1.4', 'Thuế thu nhập đã nộp cho phần thu nhập nhận được ở nước ngo i', 'B5', 0, 'B', 'TNDN', '', '', 0),
											(9, '1.5', 'Điều chỉnh tăng lợi nhuận do xác định giá thị trường đối với  giao dịch liên kết', 'B6', 0, 'B', 'TNDN', '', '', 0),
											(10, '1.6', 'Các khoản điều chỉnh làm tăng lợi nhuận trước thuế khác', 'B7', 0, 'B', 'TNDN', '', '', 0),
											(11, '2', 'Điều chỉnh giảm tổng lợi nhuận trước thuế thu nhập doanh nghiệp (B8=B9+B10+B11)', 'B8', 0, 'B', 'TNDN', '', '', 0),
											(12, '2.1', 'Giảm trừ các khoản doanh thu đã tính thuế năm trước', 'B9', 0, 'B', 'TNDN', '', '', 0),
											(13, '2.2', 'Chi phí của phần doanh thu điều chỉnh tăng', 'B10', 0, 'B', 'TNDN', '', '', 0),
											(14, '2.3', 'Các khoản điều chỉnh làm giảm lợi nhuận trước thuế khác', 'B11', 0, 'B', 'TNDN', '', '', 0),
											(15, '3', 'Tổng thu nhập chịu thuế (B12=A1+B1-B8)', 'B12', 21444076949, 'B', 'TNDN', '', '', 0),
											(16, '3.1', 'Thu nhập chịu thuế từ hoạt động sản xuất kinh doanh', 'B13', 21444076949, 'B', 'TNDN', '', '', 0),
											(17, '3.2', 'Thu nhập chịu thuế từ hoạt động chuyển nhượng bất động sản (B14=B12-B13)', 'B14', 0, 'B', 'TNDN', '', '', 0),
											(18, 'C', 'Xác định thuế thu nhập doanh nghiệp ( TNDN) phải nộp từ hoạt động sản xuất kinh doanh', 'C', 0, '0', 'TNDN', '', '', 0),
											(19, '1', 'Thu nhập chịu thuế (C1 = B13)', 'C1', 21444076949, 'C', 'TNDN', '', '', 0),
											(20, '2', 'Thu nhập miễn thuế', 'C2', 0, 'C', 'TNDN', '', '', 0),
											(21, '3', 'Chuyển lỗ và bù trừ lãi, lỗ', 'C3', 0, 'C', 'TNDN', '', '', 0),
											(22, '3.1', 'Lỗ từ hoạt động SXKD được chuyển trong kỳ', 'C3a', 0, 'C', 'TNDN', '', '', 0),
											(23, '3.2', 'Lỗ từ chuyển nhượng BĐS được bù trừ với lãi của hoạt động SXKD', 'C3b', 0, 'C', 'TNDN', '', '', 0),
											(24, '4', 'Thu nhập tính thuế (TNTT) (C4=C1-C2-C3a-C3b)', 'C4', 21444076949, 'C', 'TNDN', '', '', 0),
											(25, '5', 'Trích lập quỹ khoa học công nghệ (nếu có)', 'C5', 0, 'C', 'TNDN', '', '', 0),
											(26, '6', 'TNTT sau khi đã trích lập quỹ khoa học công nghệ (C6=C4-C5=C7+C8+C9)', 'C6', 0, 'C', 'TNDN', '', '', 0),
											(27, '6.1', 'Trong đó: + Thu nhập tính thuế tính theo thuế suất 22% (bao gồm cả thu nhập được áp dụng thuế suất ưu đãi)', 'C7', 0, 'C', 'TNDN', '', '', 0),
											(28, '6.2', '+ Thu nhập tính thuế tính theo thuế suất 20% (bao gồm cả thu nhập được áp dụng thuế suất ưu đãi)', 'C8', 0, 'C', 'TNDN', '', '', 0),
											(29, '6.3', '+ Thu nhập tính thuế tính theo thuế suất không ưu đãi khác', 'C9', 0, 'C', 'TNDN', '', '', 0),
											(30, '6.3', '+ Thuế suất không ưu đãi khác (%)', 'C9a', 0, 'C', 'TNDN', '', '', 0),
											(31, '7', 'Thuế TNDN từ hoạt động SXKD tính theo thuế suất không ưu đãi (C10 =(C7 x 22%) + (C8 x 20%) + (C9 x C9a))', 'C10', 0, 'C', 'TNDN', '', '', 0),
											(32, '8', 'Thuế TNDN chênh lệch do áp dụng mức thuế suất ưu đãi', 'C11', 0, 'C', 'TNDN', '', '', 0),
											(33, '9', 'Thuế TNDN được miễn, giảm trong kỳ', 'C12', 0, 'C', 'TNDN', '', '', 0),
											(34, '9.1', 'Trong đó: + Số thuế TNDN được miễn, giảm theo Hiệp định', 'C13', 0, 'C', 'TNDN', '', '', 0),
											(35, '9.2', '+ Số thuế TNDN được miễn, giảm không theo Luật Thuế TNDN', 'C14', 0, 'C', 'TNDN', '', '', 0),
											(36, '11', 'Số thuế thu nhập đã nộp ở nước ngoài được trừ trong kỳ tính thuế', 'C15', 0, 'C', 'TNDN', '', '', 0),
											(37, '12', 'Thuế TNDN của hoạt động sản xuất kinh doanh (C16=C10-C11-C12-C15)', 'C16', 0, 'C', 'TNDN', '', '', 0),
											(38, 'D', 'Tổng số thuế TNDN phải nộp  (D=D1+D2+D3)', 'D', 0, '0', 'TNDN', '', '', 0),
											(39, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh (D1=C16)', 'D1', 0, 'D', 'TNDN', '', '', 0),
											(40, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản', 'D2', 0, 'D', 'TNDN', '', '', 0),
											(41, '3', 'Thuế TNDN phải nộp khác (nếu có)', 'D3', 0, 'D', 'TNDN', '', '', 0),
											(42, 'E', 'Số thuế TNDN đã tạm nộp trong năm (E = E1+E2+E3)', 'E', 0, '0', 'TNDN', '', '', 0),
											(43, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh', 'E1', 0, 'E', 'TNDN', '', '', 0),
											(44, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản', 'E2', 0, 'E', 'TNDN', '', '', 0),
											(45, '3', 'Thuế TNDN phải nộp khác (nếu có)', 'E3', 0, 'E', 'TNDN', '', '', 0),
											(46, 'G', 'Tổng số thuế TNDN còn phải nộp (G = G1+G2+G3)', 'G', 0, '0', 'TNDN', '', '', 0),
											(47, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh (G1 = D1-E1)', 'G1', 0, 'G', 'TNDN', '', '', 0),
											(48, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản (G2 = D2-E2)', 'G2', 0, 'G', 'TNDN', '', '', 0),
											(49, '3', 'Thuế TNDN phải nộp khác (nếu có) (G3 = D3-E3)', 'G3', 0, 'G', 'TNDN', '', '', 0),
											(50, 'H', '20% số thuế TNDN phải nộp (H = D*20%)', 'H', 0, '0', 'TNDN', '', '', 0),
											(51, 'I', 'Chênh lệch giữa số thuế TNDN còn phải nộp với 20% số thuế TNDN phải nộp (I = G-H)', 'I', 0, '0', 'TNDN', '', '', 0),
											(52, '', 'Kết quả kinh doanh ghi nhận theo báo cáo tài chính', '', 0, '0', 'PLKQKD', '', '', 0),
											(53, '1', 'Doanh thu bán hàng và cung cấp dịch vụ', '1', 0, '0', 'PLKQKD', '511', '', 0),
											(54, '', 'Trong đó: - Doanh thu bán hàng hoá, dịch vụ xuất khẩu', '2', 0, '1', 'PLKQKD', '', '', 0),
											(55, '2', 'Các khoản giảm trừ doanh thu ([03]=[04]+[05]+[06]+[07])', '3', 0, '0', 'PLKQKD', '', '', 0),
											(56, 'a', 'Chiết khấu thương mại', '4', 0, '1', 'PLKQKD', '', '5211', 0),
											(57, 'b', 'Giảm giá hàng bán', '5', 0, '1', 'PLKQKD', '', '5212', 0),
											(58, 'c', 'Giá trị hàng bán bị trả lại', '6', 0, '1', 'PLKQKD', '', '5213', 0),
											(59, 'd', 'Thuế tiêu thụ đặc biệt, thuế xuất khẩu, thuế giá trị gia tăng theo phương pháp trực tiếp phải nộp', '7', 0, '1', 'PLKQKD', '', '', 0),
											(60, '3', 'Doanh thu hoạt động tài chính', '8', 0, '0', 'PLKQKD', '515', '', 0),
											(61, '4', 'Chi phí sản xuất, kinh doanh hàng hoá, dịch vụ ([09]=[10]+[11]+[12])', '9', 0, '0', 'PLKQKD', '', '', 0),
											(62, 'a', 'Giá vốn hàng bán', '10', 0, '1', 'PLKQKD', '', '632', 0),
											(63, 'b', 'Chi phí bán hàng', '11', 0, '1', 'PLKQKD', '', '641', 0),
											(64, 'c', 'Chi phí quản lý doanh nghiệp', '12', 0, '1', 'PLKQKD', '', '642', 0),
											(65, '5', 'Chi phí tài chính', '13', 0, '0', 'PLKQKD', '', '635', 0),
											(66, '', 'Trong đó: Chi phí lãi tiền vay dùng cho sản xuất, kinh doanh', '14', 0, '1', 'PLKQKD', '', '', 0),
											(67, '6', 'Lợi nhuận thuần từ hoạt động kinh doanh ([15]=[01]-[03]+[08]-[09]-[13])', '15', 0, '0', 'PLKQKD', '', '', 0),
											(68, '7', 'Thu nhập khác', '16', 0, '0', 'PLKQKD', '711', '', 0),
											(69, '8', 'Chi phí khác', '17', 0, '0', 'PLKQKD', '', '811', 0),
											(70, '9', 'Lợi nhuận khác ([18]=[16]-[17])', '18', 0, '0', 'PLKQKD', '', '', 0),
											(71, '10', 'Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp ([19]=[15]+[18])', '19', 0, '0', 'PLKQKD', '', '', 0),
											(72, '', '1. Doanh thu bán hàng và cung cấp dịch vụ', '01', 0, '0', 'XDKQKD', '511', '', 0),
											(73, '', '2. Các khoản giảm trừ doanh thu', '02', 0, '0', 'XDKQKD', '', '', 0),
											(74, '', '3. Doanh thu thuần về bán hàng và cung cấp dịch vụ (10=01-02)', '10', 0, '0', 'XDKQKD', '', '', 0),
											(75, '', '4. Giá vốn bán hàng', '11', 0, '0', 'XDKQKD', '', '632', 0),
											(76, '', '5. Lợi nhuận gộp về bán hàng và  cung cấp dịch vụ (20=10-11)', '20', 0, '0', 'XDKQKD', '', '', 0),
											(77, '', '6. Doanh thu hoạt động tài chính', '21', 0, '0', 'XDKQKD', '515', '', 0),
											(78, '', '7. Chi phí tài chính', '22', 0, '0', 'XDKQKD', '', '635', 0),
											(79, '', '- Trong đó: Chi phí lãi vay', '23', 0, '1', 'XDKQKD', '', '', 0),
											(99, '', '8. Chi phí bán hàng', '25', 0, '0', 'XDKQKD', '', '641', 0),
											(101, '', '9. Chi phí quản lý doanh nghiệp', '26', 0, '0', 'XDKQKD', '', '642', 0),
											(102, '', '10. Lợi nhuận thuần từ hoạt động kinh doanh (30=20+21-22-25-26)', '30', 0, '0', 'XDKQKD', '', '', 0),
											(103, '', '11. Thu nhập khác', '31', 0, '0', 'XDKQKD', '711', '', 0),
											(104, '', '12. Chi phí khác', '32', 0, '0', 'XDKQKD', '', '811', 0),
											(105, '', '13. Lợi nhuận khác (40= 31-32)', '40', 0, '0', 'XDKQKD', '', '', 0),
											(106, '', '14. Tổng lợi nhuận kế toán trước thuế (50=30+40)', '50', 0, '0', 'XDKQKD', '', '', 0),
											(107, '', '15. Chi phí thuế TNDN hiện hành', '51', 0, '0', 'XDKQKD', '', '8211', 0),
											(108, '', '16. Chi phí thuế TNDN hoãn lại', '52', 0, '0', 'XDKQKD', '', '8212', 0),
											(113, '', '17. Lợi nhuận sau thuế thu nhập doanh nghiệp (60 = 50-51-52)', '60', 0, '0', 'XDKQKD', '', '', 0),
											(114, '', '18. Lãi cơ bản trên cổ phiếu (*)', '70', 0, '0', 'XDKQKD', '', '', 0),
											(115, '', '19. Lãi suy giảm trên cổ phiếu (*)', '71', 0, '0', 'XDKQKD', '', '', 0);");
} else {
    $OBJ->re_query("INSERT INTO `tokhaitndn` (`sott`, `maso`, `chitieu`, `machitieu`, `sotien`, `machitieucha`, `loaitokhai`, `matk`, `tkno`, `sotiendk`) VALUES
											(2, '1', 'Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp', 'A1', 0, 'A', 'TNDN', '', '', 0),
											(3, 'B', 'Xác định thu nhập chịu thuế theo Luật thuế thu nhập doanh nghiệp', 'B', 0, '0', 'TNDN', '', '', 0),
											(4, '1', 'Điều chỉnh tăng tổng lợi nhuận trước thuế thu nhập doanh nghiệp  (B1= B2+B3+B4+B5+B6 +B7)', 'B1', 0, 'B', 'TNDN', '', '', 0),
											(5, '1.1', 'Các khoản điều chỉnh tăng doanh thu', 'B2', 0, 'B', 'TNDN', '', '', 0),
											(6, '1.2', 'Chi phí của phần doanh thu điều chỉnh giảm', 'B3', 0, 'B', 'TNDN', '', '', 0),
											(7, '1.3', 'Các khoản chi không được trừ khi xác định thu nhập chịu thuế', 'B4', 0, 'B', 'TNDN', '', '', 0),
											(8, '1.4', 'Thuế thu nhập đã nộp cho phần thu nhập nhận được ở nước ngo i', 'B5', 0, 'B', 'TNDN', '', '', 0),
											(9, '1.5', 'Điều chỉnh tăng lợi nhuận do xác định giá thị trường đối với  giao dịch liên kết', 'B6', 0, 'B', 'TNDN', '', '', 0),
											(10, '1.6', 'Các khoản điều chỉnh làm tăng lợi nhuận trước thuế khác', 'B7', 0, 'B', 'TNDN', '', '', 0),
											(11, '2', 'Điều chỉnh giảm tổng lợi nhuận trước thuế thu nhập doanh nghiệp (B8=B9+B10+B11)', 'B8', 0, 'B', 'TNDN', '', '', 0),
											(12, '2.1', 'Giảm trừ các khoản doanh thu đã tính thuế năm trước', 'B9', 0, 'B', 'TNDN', '', '', 0),
											(13, '2.2', 'Chi phí của phần doanh thu điều chỉnh tăng', 'B10', 0, 'B', 'TNDN', '', '', 0),
											(14, '2.3', 'Các khoản điều chỉnh làm giảm lợi nhuận trước thuế khác', 'B11', 0, 'B', 'TNDN', '', '', 0),
											(15, '3', 'Tổng thu nhập chịu thuế (B12=A1+B1-B8)', 'B12', 0, 'B', 'TNDN', '', '', 0),
											(16, '3.1', 'Thu nhập chịu thuế từ hoạt động sản xuất kinh doanh', 'B13', 0, 'B', 'TNDN', '', '', 0),
											(17, '3.2', 'Thu nhập chịu thuế từ hoạt động chuyển nhượng bất động sản (B14=B12-B13)', 'B14', 0, 'B', 'TNDN', '', '', 0),
											(18, 'C', 'Xác định thuế thu nhập doanh nghiệp ( TNDN) phải nộp từ hoạt động sản xuất kinh doanh', 'C', 0, '0', 'TNDN', '', '', 0),
											(19, '1', 'Thu nhập chịu thuế (C1 = B13)', 'C1', 0, 'C', 'TNDN', '', '', 0),
											(20, '2', 'Thu nhập miễn thuế', 'C2', 0, 'C', 'TNDN', '', '', 0),
											(21, '3', 'Chuyển lỗ và bù trừ lãi, lỗ', 'C3', 0, 'C', 'TNDN', '', '', 0),
											(22, '3.1', 'Lỗ từ hoạt động SXKD được chuyển trong kỳ', 'C3a', 0, 'C', 'TNDN', '', '', 0),
											(23, '3.2', 'Lỗ từ chuyển nhượng BĐS được bù trừ với lãi của hoạt động SXKD', 'C3b', 0, 'C', 'TNDN', '', '', 0),
											(24, '4', 'Thu nhập tính thuế (TNTT) (C4=C1-C2-C3a-C3b)', 'C4', 0, 'C', 'TNDN', '', '', 0),
											(25, '5', 'Trích lập quỹ khoa học công nghệ (nếu có)', 'C5', 0, 'C', 'TNDN', '', '', 0),
											(26, '6', 'TNTT sau khi đã trích lập quỹ khoa học công nghệ (C6=C4-C5=C7+C8+C9)', 'C6', 0, 'C', 'TNDN', '', '', 0),
											(27, '6.1', 'Trong đó: + Thu nhập tính thuế tính theo thuế suất 22% (bao gồm cả thu nhập được áp dụng thuế suất ưu đãi)', 'C7', 0, 'C', 'TNDN', '', '', 0),
											(28, '6.2', '+ Thu nhập tính thuế tính theo thuế suất 20% (bao gồm cả thu nhập được áp dụng thuế suất ưu đãi)', 'C8', 0, 'C', 'TNDN', '', '', 0),
											(29, '6.3', '+ Thu nhập tính thuế tính theo thuế suất không ưu đãi khác', 'C9', 0, 'C', 'TNDN', '', '', 0),
											(30, '6.3', '+ Thuế suất không ưu đãi khác (%)', 'C9a', 0, 'C', 'TNDN', '', '', 0),
											(31, '7', 'Thuế TNDN từ hoạt động SXKD tính theo thuế suất không ưu đãi (C10 =(C7 x 22%) + (C8 x 20%) + (C9 x C9a))', 'C10', 0, 'C', 'TNDN', '', '', 0),
											(32, '8', 'Thuế TNDN chênh lệch do áp dụng mức thuế suất ưu đãi', 'C11', 0, 'C', 'TNDN', '', '', 0),
											(33, '9', 'Thuế TNDN được miễn, giảm trong kỳ', 'C12', 0, 'C', 'TNDN', '', '', 0),
											(34, '9.1', 'Trong đó: + Số thuế TNDN được miễn, giảm theo Hiệp định', 'C13', 0, 'C', 'TNDN', '', '', 0),
											(35, '9.2', '+ Số thuế TNDN được miễn, giảm không theo Luật Thuế TNDN', 'C14', 0, 'C', 'TNDN', '', '', 0),
											(36, '11', 'Số thuế thu nhập đã nộp ở nước ngoài được trừ trong kỳ tính thuế', 'C15', 0, 'C', 'TNDN', '', '', 0),
											(37, '12', 'Thuế TNDN của hoạt động sản xuất kinh doanh (C16=C10-C11-C12-C15)', 'C16', 0, 'C', 'TNDN', '', '', 0),
											(38, 'D', 'Tổng số thuế TNDN phải nộp  (D=D1+D2+D3)', 'D', 0, '0', 'TNDN', '', '', 0),
											(39, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh (D1=C16)', 'D1', 0, 'D', 'TNDN', '', '', 0),
											(40, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản', 'D2', 0, 'D', 'TNDN', '', '', 0),
											(41, '3', 'Thuế TNDN phải nộp khác (nếu có)', 'D3', 0, 'D', 'TNDN', '', '', 0),
											(42, 'E', 'Số thuế TNDN đã tạm nộp trong năm (E = E1+E2+E3)', 'E', 0, '0', 'TNDN', '', '', 0),
											(43, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh', 'E1', 0, 'E', 'TNDN', '', '', 0),
											(44, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản', 'E2', 0, 'E', 'TNDN', '', '', 0),
											(45, '3', 'Thuế TNDN phải nộp khác (nếu có)', 'E3', 0, 'E', 'TNDN', '', '', 0),
											(46, 'G', 'Tổng số thuế TNDN còn phải nộp (G = G1+G2+G3)', 'G', 0, '0', 'TNDN', '', '', 0),
											(47, '1', 'Thuế TNDN của hoạt động sản xuất kinh doanh (G1 = D1-E1)', 'G1', 0, 'G', 'TNDN', '', '', 0),
											(48, '2', 'Thuế TNDN từ hoạt động chuyển nhượng bất động sản (G2 = D2-E2)', 'G2', 0, 'G', 'TNDN', '', '', 0),
											(49, '3', 'Thuế TNDN phải nộp khác (nếu có) (G3 = D3-E3)', 'G3', 0, 'G', 'TNDN', '', '', 0),
											(50, 'H', '20% số thuế TNDN phải nộp (H = D*20%)', 'H', 0, '0', 'TNDN', '', '', 0),
											(51, 'I', 'Chênh lệch giữa số thuế TNDN còn phải nộp với 20% số thuế TNDN phải nộp (I = G-H)', 'I', 0, '0', 'TNDN', '', '', 0),
											(52, '', 'Kết quả kinh doanh ghi nhận theo báo cáo tài chính', '', 0, '0', 'PLKQKD', '', '', 0),
											(53, '1', 'Doanh thu bán hàng và cung cấp dịch vụ', '1', 0, '0', 'PLKQKD', '511', '', 0),
											(54, '', 'Trong đó: - Doanh thu bán hàng hoá, dịch vụ xuất khẩu', '2', 0, '1', 'PLKQKD', '', '', 0),
											(55, '2', 'Các khoản giảm trừ doanh thu ([03]=[04]+[05]+[06]+[07])', '3', 0, '0', 'PLKQKD', '', '', 0),
											(56, 'a', 'Chiết khấu thương mại', '4', 0, '1', 'PLKQKD', '', '', 0),
											(57, 'b', 'Giảm giá hàng bán', '5', 0, '1', 'PLKQKD', '', '', 0),
											(58, 'c', 'Giá trị hàng bán bị trả lại', '6', 0, '1', 'PLKQKD', '', '', 0),
											(59, 'd', 'Thuế tiêu thụ đặc biệt, thuế xuất khẩu, thuế giá trị gia tăng theo phương pháp trực tiếp phải nộp', '7', 0, '1', 'PLKQKD', '', '', 0),
											(60, '3', 'Doanh thu hoạt động tài chính', '8', 0, '0', 'PLKQKD', '515', '', 0),
											(61, '4', 'Chi phí sản xuất, kinh doanh hàng hoá, dịch vụ ([09]=[10]+[11]+[12])', '9', 0, '0', 'PLKQKD', '', '', 0),
											(62, 'a', 'Giá vốn hàng bán', '10', 0, '1', 'PLKQKD', '', '632', 0),
											(63, 'b', 'Chi phí bán hàng', '11', 0, '1', 'PLKQKD', '', '6421', 0),
											(64, 'c', 'Chi phí quản lý doanh nghiệp', '12', 0, '1', 'PLKQKD', '', '6422', 0),
											(65, '5', 'Chi phí tài chính', '13', 0, '0', 'PLKQKD', '', '635', 0),
											(66, '', 'Trong đó: Chi phí lãi tiền vay dùng cho sản xuất, kinh doanh', '14', 0, '1', 'PLKQKD', '', '', 0),
											(67, '6', 'Lợi nhuận thuần từ hoạt động kinh doanh ([15]=[01]-[03]+[08]-[09]-[13])', '15', 0, '0', 'PLKQKD', '', '', 0),
											(68, '7', 'Thu nhập khác', '16', 0, '0', 'PLKQKD', '711', '', 0),
											(69, '8', 'Chi phí khác', '17', 0, '0', 'PLKQKD', '', '811', 0),
											(70, '9', 'Lợi nhuận khác ([18]=[16]-[17])', '18', 0, '0', 'PLKQKD', '', '', 0),
											(71, '10', 'Tổng lợi nhuận kế toán trước thuế thu nhập doanh nghiệp ([19]=[15]+[18])', '19', 0, '0', 'PLKQKD', '', '', 0),
											(72, '', '1. Doanh thu bán hàng và cung cấp dịch vụ', '01', 0, '0', 'XDKQKD', '511', '', 0),
											(73, '', '2. Các khoản giảm trừ doanh thu', '02', 0, '0', 'XDKQKD', '', '', 0),
											(74, '', '3. Doanh thu thuần về bán hàng và cung cấp dịch vụ (10=01-02)', '10', 0, '0', 'XDKQKD', '', '', 0),
											(75, '', '4. Giá vốn bán hàng', '11', 0, '0', 'XDKQKD', '', '632', 0),
											(76, '', '5. Lợi nhuận gộp về bán hàng và  cung cấp dịch vụ (20=10-11)', '20', 0, '0', 'XDKQKD', '', '', 0),
											(77, '', '6. Doanh thu hoạt động tài chính', '21', 0, '0', 'XDKQKD', '515', '', 0),
											(78, '', '7. Chi phí tài chính', '22', 0, '0', 'XDKQKD', '', '635', 0),
											(79, '', '- Trong đó: Chi phí lãi vay', '23', 0, '1', 'XDKQKD', '', '', 0),
											(80, '', '8. Chi phí quản lý kinh doanh', '24', 0, '0', 'XDKQKD', '', '642', 0),
											(81, '', '9. Lợi nhuận thuần từ hoạt động kinh doanh (30=20+21-22-24)', '30', 0, '0', 'XDKQKD', '', '', 0),
											(82, '', '10. Thu nhập khác', '31', 0, '0', 'XDKQKD', '711', '', 0),
											(83, '', '11. Chi phí khác', '32', 0, '0', 'XDKQKD', '', '811', 0),
											(84, '', '12. Lợi nhuận khác (40= 31-32)', '40', 0, '0', 'XDKQKD', '', '', 0),
											(85, '', '13. Tổng lợi nhuận kế toán trước thuế (50=30+40)', '50', 0, '0', 'XDKQKD', '', '', 0),
											(86, '', '14. Chi phí thuế TNDN', '51', 0, '0', 'XDKQKD', '', '', 0),
											(87, '', '15. Lợi nhuận sau thuế thu nhập doanh nghiệp (60 = 50-51)', '60', 0, '0', 'XDKQKD', '', '', 0);");
}
}
echo "Dữ liệu đã cập nhật thành công bảng lưu chuyển tiền tệ";
?>
